version: '3.8'

services:
  test_web:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - test_app
  
  test_app:
    restart: always
    build:
      context: ./node
    ports:
      - 5001:5001
    expose:
      - 5001
    depends_on:
      - test_db
  
  test_db:
    restart: unless-stopped
    build:
      context: ./mysql
    hostname: "docker-mysql"
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: nodeprac
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234